<?xml version="1.0" encoding="utf-8"?><Database Name="HavanaRealEstate" Class="HavanadataclassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=AMIT-PC\SQLEXPRESS;Initial Catalog=HavanaRealEstate;Integrated Security=True" SettingsObjectName="HavanaDAL.Properties.Settings" SettingsPropertyName="HavanaRealEstateConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.FeebackRply" Member="FeebackRplies">
    <Type Name="FeebackRply">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RplyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Rply" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Updt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Crdt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tblfeedback_FeebackRply" Member="tblfeedback" ThisKey="RplyId" OtherKey="Id" Type="tblfeedback" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblavailableblocks" Member="tblavailableblocks">
    <Type Name="tblavailableblock">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BlockId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BlockNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsBooked" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Crdt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Updt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tblblockcategory_tblavailableblock" Member="tblblockcategory" ThisKey="BlockId" OtherKey="Id" Type="tblblockcategory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblbank" Member="tblbanks">
    <Type Name="tblbank">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RegId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BankName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="BankBranch" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="IFSC" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="AccountNo" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Updt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Crdt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tblreg_tblbank" Member="tblreg" ThisKey="RegId" OtherKey="Id" Type="tblreg" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblblockcategory" Member="tblblockcategories">
    <Type Name="tblblockcategory">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BlockName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Crdt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Updt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tblblockcategory_tblavailableblock" Member="tblavailableblocks" ThisKey="Id" OtherKey="BlockId" Type="tblavailableblock" />
    </Type>
  </Table>
  <Table Name="dbo.tblcontactus" Member="tblcontactus">
    <Type Name="tblcontactus">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Contact" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Message" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Updt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Crdt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tblcontactus_tblrplycontact" Member="tblrplycontacts" ThisKey="Id" OtherKey="ContactId" Type="tblrplycontact" />
    </Type>
  </Table>
  <Table Name="dbo.tblfeedback" Member="tblfeedbacks">
    <Type Name="tblfeedback">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Msg" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Rating" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="Updt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Crdt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tblfeedback_FeebackRply" Member="FeebackRplies" ThisKey="Id" OtherKey="RplyId" Type="FeebackRply" />
    </Type>
  </Table>
  <Table Name="dbo.tblkyc" Member="tblkycs">
    <Type Name="tblkyc">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RegId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Pan" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Aadhaar" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Updt" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Crdt" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tblreg_tblkyc" Member="tblreg" ThisKey="RegId" OtherKey="Id" Type="tblreg" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblPlanCharges" Member="tblPlanCharges">
    <Type Name="tblPlanCharge">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlanId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EMI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Total EMIs]" Member="Total_EMIs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Updt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Crdt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[Extra Charges]" Member="Extra_Charges" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Association Name="tblPlansMaster_tblPlanCharge" Member="tblPlansMaster" ThisKey="PlanId" OtherKey="Id" Type="tblPlansMaster" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblPlansMaster" Member="tblPlansMasters">
    <Type Name="tblPlansMaster">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlanName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Updt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Crdt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tblPlansMaster_tblPlanCharge" Member="tblPlanCharges" ThisKey="Id" OtherKey="PlanId" Type="tblPlanCharge" />
    </Type>
  </Table>
  <Table Name="dbo.tblprofile" Member="tblprofiles">
    <Type Name="tblprofile">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RegId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Picture" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="State" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Pin" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Updt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Crdt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tblreg_tblprofile" Member="tblreg" ThisKey="RegId" OtherKey="Id" Type="tblreg" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblProperties" Member="tblProperties">
    <Type Name="tblProperty">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Price" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Bedroom" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bathroom" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Area" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="[For]" Member="For" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="Updt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Crdt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblreg" Member="tblregs">
    <Type Name="tblreg">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RegNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ContactNo" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(16)" CanBeNull="true" />
      <Column Name="IsVerified" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Updt" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Crdt" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tblreg_tblbank" Member="tblbanks" ThisKey="Id" OtherKey="RegId" Type="tblbank" />
      <Association Name="tblreg_tblkyc" Member="tblkycs" ThisKey="Id" OtherKey="RegId" Type="tblkyc" />
      <Association Name="tblreg_tblprofile" Member="tblprofiles" ThisKey="Id" OtherKey="RegId" Type="tblprofile" />
    </Type>
  </Table>
  <Table Name="dbo.tblrplycontact" Member="tblrplycontacts">
    <Type Name="tblrplycontact">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ContactId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Rply" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="Crdt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Updt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tblcontactus_tblrplycontact" Member="tblcontactus" ThisKey="ContactId" OtherKey="Id" Type="tblcontactus" IsForeignKey="true" />
    </Type>
  </Table>
</Database>